### Importing required packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

### Importing the dataset

In [2]:
MB_Train_data = pd.read_csv("train.csv")
MB_Test_data = pd.read_csv("test.csv")

### Performing EDA and Preprocessing on the given dataset

In [3]:
MB_Train_data.shape,MB_Test_data.shape

((4209, 378), (4209, 377))

In [4]:
MB_Train_data.size,MB_Test_data.size

(1591002, 1586793)

In [5]:
MB_Train_data.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
MB_Train_data.dtypes

ID        int64
y       float64
X0       object
X1       object
X2       object
         ...
X380      int64
X382      int64
X383      int64
X384      int64
X385      int64
Length: 378, dtype: object

In [7]:
MB_Train_data.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)

In [8]:
MB_Train_data = pd.DataFrame(MB_Train_data)

**Finding the unique values in the train datatset**

In [9]:
Column_values = MB_Train_data.values.ravel()
Unique_values = pd.unique(Column_values)
print(Unique_values)

[0 130.81 'k' ... 8415 87.48 8417]

**Finding the unique values in the test datatset**

In [10]:
Column_values2 = MB_Test_data.values.ravel()
Unique_values2 = pd.unique(Column_values2)
print(Unique_values2)

[1 'az' 'v' ... 8413 8414 8416]

**Droping the column named 'ID' from the train set**

In [11]:
MB_Train_data = MB_Train_data.drop(['ID'], axis = 1)
MB_Train_data

,y,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,130.81,k,v,at,a,d,u,j,o,0,...,0,0,1,0,0,0,0,0,0,0
1,88.53,k,t,av,e,d,y,l,o,0,...,1,0,0,0,0,0,0,0,0,0
2,76.26,az,w,n,c,d,x,j,x,0,...,0,0,0,0,0,0,1,0,0,0
3,80.62,az,t,n,f,d,x,l,e,0,...,0,0,0,0,0,0,0,0,0,0
4,78.02,az,v,n,f,d,h,d,n,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,107.39,ak,s,as,c,d,aa,d,q,0,...,1,0,0,0,0,0,0,0,0,0
4205,108.77,j,o,t,d,d,aa,h,h,0,...,0,1,0,0,0,0,0,0,0,0
4206,109.22,ak,v,r,a,d,aa,g,e,0,...,0,0,1,0,0,0,0,0,0,0
4207,87.48,al,r,e,f,d,aa,l,u,0,...,0,0,0,0,0,0,0,0,0,0
4208,110.85,z,r,ae,c,d,aa,g,w,0,...,1,0,0,0,0,0,0,0,0,0

**Checking the null values in the train datatset**

In [12]:
MB_Train_data.isnull().sum()

y       0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 377, dtype: int64

**Checking the null values in the test datatset**

In [13]:
MB_Test_data.isnull().sum()

ID      0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 377, dtype: int64

**Using Labelencoder to convert the categorical data into numeric for the train set**

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
MB_Train_data['X0'] = le.fit_transform(MB_Train_data['X0'])
MB_Train_data['X1'] = le.fit_transform(MB_Train_data['X1'])
MB_Train_data['X2'] = le.fit_transform(MB_Train_data['X2'])
MB_Train_data['X3'] = le.fit_transform(MB_Train_data['X3'])
MB_Train_data['X4'] = le.fit_transform(MB_Train_data['X4'])
MB_Train_data['X5'] = le.fit_transform(MB_Train_data['X5'])
MB_Train_data['X6'] = le.fit_transform(MB_Train_data['X6'])
MB_Train_data['X8'] = le.fit_transform(MB_Train_data['X8'])

In [15]:
MB_Train_data

,y,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,130.81,32,23,17,0,3,24,9,14,0,...,0,0,1,0,0,0,0,0,0,0
1,88.53,32,21,19,4,3,28,11,14,0,...,1,0,0,0,0,0,0,0,0,0
2,76.26,20,24,34,2,3,27,9,23,0,...,0,0,0,0,0,0,1,0,0,0
3,80.62,20,21,34,5,3,27,11,4,0,...,0,0,0,0,0,0,0,0,0,0
4,78.02,20,23,34,5,3,12,3,13,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,107.39,8,20,16,2,3,0,3,16,0,...,1,0,0,0,0,0,0,0,0,0
4205,108.77,31,16,40,3,3,0,7,7,0,...,0,1,0,0,0,0,0,0,0,0
4206,109.22,8,23,38,0,3,0,6,4,0,...,0,0,1,0,0,0,0,0,0,0
4207,87.48,9,19,25,5,3,0,11,20,0,...,0,0,0,0,0,0,0,0,0,0
4208,110.85,46,19,3,2,3,0,6,22,0,...,1,0,0,0,0,0,0,0,0,0

**Droping the features having zero variance from the train set**

In [16]:
from sklearn.feature_selection import VarianceThreshold
Var_Threshold = VarianceThreshold(threshold=0)
Var_Threshold.fit(MB_Train_data)

VarianceThreshold(threshold=0)

In [17]:
Var_Threshold.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [18]:
MB_Train_data.columns[Var_Threshold.get_support()]

Index(['y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=365)

In [19]:
Zero_variance_col = [column for column in MB_Train_data.columns
                    if column not in MB_Train_data.columns[Var_Threshold.get_support()]]
print(len(Zero_variance_col))

12

In [20]:
for feature in Zero_variance_col:
    print(feature)

X11
X93
X107
X233
X235
X268
X289
X290
X293
X297
X330
X347

In [21]:
MB_Train_data.drop(Zero_variance_col, axis =1)

,y,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,130.81,32,23,17,0,3,24,9,14,0,...,0,0,1,0,0,0,0,0,0,0
1,88.53,32,21,19,4,3,28,11,14,0,...,1,0,0,0,0,0,0,0,0,0
2,76.26,20,24,34,2,3,27,9,23,0,...,0,0,0,0,0,0,1,0,0,0
3,80.62,20,21,34,5,3,27,11,4,0,...,0,0,0,0,0,0,0,0,0,0
4,78.02,20,23,34,5,3,12,3,13,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,107.39,8,20,16,2,3,0,3,16,0,...,1,0,0,0,0,0,0,0,0,0
4205,108.77,31,16,40,3,3,0,7,7,0,...,0,1,0,0,0,0,0,0,0,0
4206,109.22,8,23,38,0,3,0,6,4,0,...,0,0,1,0,0,0,0,0,0,0
4207,87.48,9,19,25,5,3,0,11,20,0,...,0,0,0,0,0,0,0,0,0,0
4208,110.85,46,19,3,2,3,0,6,22,0,...,1,0,0,0,0,0,0,0,0,0

**Droping the column named 'ID' from the test set**

In [22]:
MB_Test_data.drop(['ID'], axis = 1, inplace = True)

**Using Labelencoder to convert the categorical data into numeric for the test set**

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
MB_Test_data['X0'] = le.fit_transform(MB_Test_data['X0'])
MB_Test_data['X1'] = le.fit_transform(MB_Test_data['X1'])
MB_Test_data['X2'] = le.fit_transform(MB_Test_data['X2'])
MB_Test_data['X3'] = le.fit_transform(MB_Test_data['X3'])
MB_Test_data['X4'] = le.fit_transform(MB_Test_data['X4'])
MB_Test_data['X5'] = le.fit_transform(MB_Test_data['X5'])
MB_Test_data['X6'] = le.fit_transform(MB_Test_data['X6'])
MB_Test_data['X8'] = le.fit_transform(MB_Test_data['X8'])

**Droping the features having zero variance from the test set**

In [24]:
from sklearn.feature_selection import VarianceThreshold
Var_Threshold2 = VarianceThreshold(threshold=0)
Var_Threshold2.fit(MB_Test_data)
Var_Threshold2.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [25]:
Zero_variance_col2 = [column for column in MB_Test_data.columns
                    if column not in MB_Test_data.columns[Var_Threshold2.get_support()]]
print(len(Zero_variance_col2))

5

In [26]:
MB_Test_data.drop(Zero_variance_col2, axis =1)

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,21,23,34,5,3,26,0,22,0,0,...,0,0,0,1,0,0,0,0,0,0
1,42,3,8,0,3,9,6,24,0,0,...,0,0,1,0,0,0,0,0,0,0
2,21,23,17,5,3,0,9,9,0,0,...,0,0,0,1,0,0,0,0,0,0
3,21,13,34,5,3,31,11,13,0,0,...,0,0,0,1,0,0,0,0,0,0
4,45,20,17,2,3,30,8,12,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,6,9,17,5,3,1,9,4,0,0,...,0,0,0,0,0,0,0,0,0,0
4205,42,1,8,3,3,1,9,24,0,0,...,0,1,0,0,0,0,0,0,0,0
4206,47,23,17,5,3,1,3,22,0,0,...,0,0,0,0,0,0,0,0,0,0
4207,7,23,17,0,3,1,2,16,0,0,...,0,0,1,0,0,0,0,0,0,0
4208,42,1,8,2,3,1,6,17,0,0,...,1,0,0,0,0,0,0,0,0,0

**Selecting the features and label from the train set and performing the split**

In [27]:
features = MB_Train_data.iloc[:,1:]
target= MB_Train_data.iloc[:,0]

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, train_size=0.80, random_state = 4)

from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler().fit(X_train)
X_train_scaled = scaling.transform(X_train)
test_scaled = scaling.transform(MB_Test_data)

In [29]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(3367, 376)
(3367,)
(842, 376)
(842,)

### Performing linear regression

In [30]:
from sklearn.linear_model import LinearRegression
lireg = LinearRegression()
lireg.fit(X_train,y_train)

LinearRegression()

In [31]:
y_pred = lireg.predict(X_test)
y_pred

array([9.19848633e+01, 9.34497070e+01, 1.10721191e+02, 9.56000977e+01,
       1.06713867e+02, 1.11549805e+02, 1.11716797e+02, 9.21025391e+01,
       9.49516602e+01, 9.62851562e+01, 9.57060547e+01, 1.17890137e+02,
       9.55913086e+01, 9.66889648e+01, 1.06465332e+02, 1.05773438e+02,
       9.75791016e+01, 9.27871094e+01, 1.04367676e+02, 1.05144043e+02,
       1.11470215e+02, 1.09887695e+02, 9.31967773e+01, 9.52104492e+01,
       9.16118164e+01, 9.46079102e+01, 9.30703125e+01, 9.38657227e+01,
       9.35332031e+01, 1.08580566e+02, 1.11842285e+02, 1.09410645e+02,
       8.71000977e+01, 9.50893555e+01, 7.74716797e+01, 1.11971191e+02,
       1.07784180e+02, 9.46206055e+01, 1.10869629e+02, 9.39819336e+01,
       1.11739746e+02, 1.04825684e+02, 9.33813477e+01, 9.53735352e+01,
       9.88212891e+01, 1.10405762e+02, 1.12986816e+02, 1.04784668e+02,
       9.30024414e+01, 9.42001953e+01, 8.94204102e+01, 9.62626953e+01,
       1.08240723e+02, 1.09164551e+02, 1.12312988e+02, 1.02771484e+02,
       9.52065430e+01, 9.38334961e+01, 9.12622070e+01, 9.27275391e+01,
       9.42426758e+01, 9.42924805e+01, 1.11236816e+02, 1.11566895e+02,
       1.06584473e+02, 9.39052734e+01, 9.66938477e+01, 9.46059570e+01,
       8.80957031e+01, 1.12308105e+02, 9.36899414e+01, 7.82436523e+01,
       1.11730957e+02, 1.10427734e+02, 9.24843750e+01, 9.65424805e+01,
       1.12875000e+02, 9.37089844e+01, 7.42851562e+01, 1.15229004e+02,
       7.74858398e+01, 1.12091309e+02, 1.12202637e+02, 1.14346191e+02,
       1.16583496e+02, 9.12612305e+01, 1.11073242e+02, 7.24501953e+01,
       9.76040039e+01, 9.65454102e+01, 9.36557617e+01, 9.04770508e+01,
       9.27714844e+01, 9.36152344e+01, 1.03545410e+02, 9.35156250e+01,
       1.16087891e+02, 9.34423828e+01, 9.59389648e+01, 9.63295898e+01,
       1.20058105e+02, 1.11851074e+02, 1.08247070e+02, 9.55581055e+01,
       9.98037109e+01, 1.12153809e+02, 1.15914551e+02, 9.53730469e+01,
       9.54262695e+01, 1.13390137e+02, 1.08618652e+02, 7.90791016e+01,
       9.68291016e+01, 1.11685059e+02, 1.01843262e+02, 9.56665039e+01,
       1.05949219e+02, 9.28266602e+01, 1.10663086e+02, 9.19130859e+01,
       9.26679688e+01, 1.09924316e+02, 1.09482910e+02, 1.00350098e+02,
       1.03226074e+02, 1.13110840e+02, 9.24096680e+01, 9.38588867e+01,
       1.10770996e+02, 1.13566895e+02, 9.39731445e+01, 1.09717285e+02,
       1.08409668e+02, 1.11596191e+02, 9.56972656e+01, 9.59155273e+01,
       1.11006348e+02, 9.08178711e+01, 9.56899414e+01, 1.00350098e+02,
       9.29394531e+01, 1.13297363e+02, 1.11604492e+02, 1.13323242e+02,
       1.12702148e+02, 1.10037109e+02, 8.99833984e+01, 1.12457031e+02,
       7.78891602e+01, 1.08159668e+02, 9.52104492e+01, 1.13062988e+02,
       9.28432617e+01, 9.05844727e+01, 9.55063477e+01, 9.41645508e+01,
       1.04093262e+02, 9.40258789e+01, 1.13804199e+02, 1.02615723e+02,
       9.44321289e+01, 1.11286621e+02, 8.89252930e+01, 9.65581055e+01,
       1.11336914e+02, 1.11753418e+02, 1.16624512e+02, 1.03062012e+02,
       1.08604004e+02, 9.36757812e+01, 1.09434082e+02, 9.11137695e+01,
       1.15829102e+02, 1.12055664e+02, 8.40400391e+01, 1.04698730e+02,
       1.00488770e+02, 9.58706055e+01, 9.06186523e+01, 9.74335938e+01,
       9.14370117e+01, 9.72202148e+01, 9.12529297e+01, 1.09652832e+02,
       1.12938965e+02, 1.11070312e+02, 9.39360352e+01, 1.04118164e+02,
       1.11284668e+02, 1.13410645e+02, 9.58964844e+01, 9.52031250e+01,
       8.79873047e+01, 1.08945801e+02, 9.55283203e+01, 9.74565430e+01,
       1.11336426e+02, 1.11999512e+02, 1.11672363e+02, 1.00206543e+02,
       1.08941895e+02, 8.66948242e+01, 1.05941895e+02, 1.06670898e+02,
       1.12164551e+02, 9.48110352e+01, 9.55395508e+01, 9.59223633e+01,
       9.73759766e+01, 9.50439453e+01, 1.05022949e+02, 1.12753418e+02,
       1.10566895e+02, 1.13070801e+02, 1.13251465e+02, 1.10584961e+02,
       1.13238281e+02, 9.84414062e+01, 1.07283691e+02, 9.15058594e+01,
       1.03030762e+02, 8.93964844e+01, 7.90434570e+01, 9.33369141e+01,
       1.13752930e+02, 1.01832520e+02, 1.01469238e+02, 1.03138672e+02,
       1.11716797e+02, 1.20071289e+02, 9.35937500e+01, 1.21261719e+02,
       9.41020508e+01, 9.00996094e+01, 9.28930664e+01, 9.24936523e+01,
       1.12352539e+02, 9.12519531e+01, 1.06187012e+02, 5.83373291e+11,
       9.46030273e+01, 7.76333008e+01, 1.11470215e+02, 1.17561035e+02,
       1.13736816e+02, 8.96870117e+01, 9.71430664e+01, 9.36083984e+01,
       1.05992188e+02, 9.56586914e+01, 1.11806641e+02, 9.39370117e+01,
       1.12371582e+02, 9.32329102e+01, 5.71763841e+11, 8.77539062e+01,
       1.08110840e+02, 9.78461914e+01, 9.49086914e+01, 9.17153320e+01,
       9.59555664e+01, 9.32827148e+01, 1.13081543e+02, 1.12227539e+02,
       8.80942383e+01, 1.17306152e+02, 9.28930664e+01, 1.09954590e+02,
       9.37773438e+01, 9.88930664e+01, 8.96875000e+01, 1.02548340e+02,
       9.48676758e+01, 9.59145508e+01, 7.83525391e+01, 7.77397461e+01,
       9.49770508e+01, 8.84179688e+01, 8.73901367e+01, 1.02955566e+02,
       9.42250977e+01, 1.03092773e+02, 9.32226562e+01, 1.11016113e+02,
       1.03588867e+02, 1.07737793e+02, 1.14059082e+02, 1.04793457e+02,
       9.48559570e+01, 8.17456055e+01, 9.22338867e+01, 1.18781738e+02,
       1.16617676e+02, 9.23540039e+01, 9.12304688e+01, 1.10813477e+02,
       1.02852051e+02, 9.39008789e+01, 1.05444824e+02, 1.10013184e+02,
       1.04349121e+02, 9.51616211e+01, 9.68081055e+01, 1.77570698e+11,
       9.51625977e+01, 1.11607422e+02, 9.43354492e+01, 1.12796387e+02,
       9.52719727e+01, 1.05927246e+02, 1.11027832e+02, 9.50122070e+01,
       1.03705566e+02, 8.97329102e+01, 1.00412598e+02, 9.46450195e+01,
       9.23525391e+01, 8.98754883e+01, 1.11435059e+02, 9.31918945e+01,
       8.98559570e+01, 9.62348633e+01, 9.25922852e+01, 9.44213867e+01,
       1.12428223e+02, 9.11040039e+01, 1.12582520e+02, 1.10170410e+02,
       8.16596680e+01, 1.11196777e+02, 1.04983887e+02, 1.15283691e+02,
       9.33222656e+01, 1.10191895e+02, 9.60434570e+01, 1.03418457e+02,
       1.13671387e+02, 1.10782715e+02, 9.56665039e+01, 9.56679688e+01,
       1.15010254e+02, 9.31777344e+01, 1.06199219e+02, 9.19267578e+01,
       9.09565430e+01, 9.43671875e+01, 9.47119141e+01, 1.06587402e+02,
       9.42290039e+01, 9.01323242e+01, 9.38710938e+01, 1.10905762e+02,
       9.57290039e+01, 1.14546387e+02, 1.07344238e+02, 9.69096680e+01,
       1.11023438e+02, 1.10109863e+02, 1.12219727e+02, 9.78950195e+01,
       1.10769043e+02, 1.03840332e+02, 9.74428711e+01, 1.12032715e+02,
       9.35791016e+01, 9.27905273e+01, 1.10502441e+02, 1.15972168e+02,
       1.22979492e+02, 7.95610352e+01, 1.13160645e+02, 9.45048828e+01,
       9.08344727e+01, 1.20010742e+02, 9.36708984e+01, 8.35087891e+01,
       1.13042969e+02, 9.28188477e+01, 1.09441406e+02, 8.76577148e+01,
       9.72275391e+01, 9.57016602e+01, 1.09456055e+02, 8.95097656e+01,
       9.58774414e+01, 1.01639648e+02, 1.10526855e+02, 9.63398438e+01,
       9.58125000e+01, 9.95019531e+01, 9.16137695e+01, 9.02729492e+01,
       9.30727539e+01, 9.41772461e+01, 1.12605957e+02, 9.76469727e+01,
       1.13760254e+02, 9.41674805e+01, 9.42934570e+01, 1.01200195e+02,
       9.50581055e+01, 1.04470215e+02, 9.67089844e+01, 1.00606445e+02,
       1.05034668e+02, 1.01647949e+02, 9.28315430e+01, 1.06095215e+02,
       1.11005371e+02, 9.32543945e+01, 9.96347656e+01, 9.43203125e+01,
       9.50195312e+01, 9.39296875e+01, 1.05363770e+02, 9.50205078e+01,
       1.03059082e+02, 9.51845703e+01, 9.27534180e+01, 1.05975098e+02,
       9.35937500e+01, 7.68691406e+01, 1.12586426e+02, 1.09424316e+02,
       9.38085938e+01, 7.81489258e+01, 1.02183105e+02, 1.04329590e+02,
       9.18779297e+01, 9.38193359e+01, 1.02652344e+02, 8.75209961e+01,
       1.03784180e+02, 1.06746094e+02, 9.76733398e+01, 9.47656250e+01,
       9.23901367e+01, 9.27695312e+01, 9.47685547e+01, 1.10573730e+02,
       1.14933594e+02, 1.09899902e+02, 9.35517578e+01, 1.11888184e+02,
       9.60961914e+01, 1.10063965e+02, 1.04242188e+02, 1.05906738e+02,
       1.11603027e+02, 9.73530273e+01, 9.23735352e+01, 1.08169434e+02,
       9.55380859e+01, 9.86591797e+01, 9.24990234e+01, 1.03820801e+02,
       9.47958984e+01, 1.09367676e+02, 9.27270508e+01, 1.10625977e+02,
       1.04157715e+02, 9.13872070e+01, 9.31015625e+01, 1.14510254e+02,
       1.06654297e+02, 9.45561523e+01, 1.06833496e+02, 1.12686035e+02,
       1.08199219e+02, 1.11105469e+02, 9.10571289e+01, 9.90561523e+01,
       1.07970703e+02, 1.08960449e+02, 1.04498047e+02, 1.12893066e+02,
       1.07819824e+02, 1.11756348e+02, 9.50644531e+01, 9.20141602e+01,
       1.13103516e+02, 9.21977539e+01, 1.04063965e+02, 7.73041992e+01,
       9.41523438e+01, 1.04538574e+02, 9.38261719e+01, 9.41289062e+01,
       1.12514160e+02, 9.13295898e+01, 1.10231934e+02, 1.09963379e+02,
       1.07170898e+02, 9.42011719e+01, 9.59326172e+01, 9.29008789e+01,
       9.61557617e+01, 9.66508789e+01, 1.04839355e+02, 8.71455078e+01,
       1.10977539e+02, 9.59692383e+01, 1.01401367e+02, 9.54775391e+01,
       1.12335938e+02, 1.13616211e+02, 1.19266602e+02, 1.10646484e+02,
       9.36523438e+01, 1.12145996e+02, 1.04058105e+02, 7.62651367e+01,
       9.27978516e+01, 1.15347168e+02, 1.10898926e+02, 9.23896484e+01,
       1.12368164e+02, 7.55327148e+01, 1.05451660e+02, 1.03632812e+02,
       9.38955078e+01, 1.13304688e+02, 9.53559570e+01, 9.19262695e+01,
       9.45493164e+01, 1.02034180e+02, 9.31909180e+01, 1.15059082e+02,
       1.13407715e+02, 9.39672852e+01, 1.13081543e+02, 9.58559570e+01,
       7.73911133e+01, 1.08782715e+02, 9.36333008e+01, 9.39262695e+01,
       1.04761230e+02, 1.11605469e+02, 7.39521484e+01, 1.16920410e+02,
       1.13450195e+02, 9.56704102e+01, 9.52485352e+01, 1.09723633e+02,
       7.72563477e+01, 1.03318848e+02, 1.11086426e+02, 1.00933105e+02,
       1.01875488e+02, 1.06756348e+02, 9.57080078e+01, 9.21547852e+01,
       9.71455078e+01, 1.02897461e+02, 1.15360840e+02, 1.09481934e+02,
       9.25434570e+01, 1.02632324e+02, 1.13049805e+02, 1.19159668e+02,
       9.57685547e+01, 1.08558105e+02, 9.24609375e+01, 1.18368652e+02,
       9.60322266e+01, 1.10032227e+02, 1.04246582e+02, 9.20961914e+01,
       1.12458496e+02, 9.48652344e+01, 1.03607422e+02, 9.17094727e+01,
       1.12620605e+02, 1.02940430e+02, 1.20446289e+02, 9.18535156e+01,
       9.75146484e+01, 1.11445801e+02, 9.56274414e+01, 9.61088867e+01,
       1.19658691e+02, 9.43647461e+01, 9.57753906e+01, 9.14096680e+01,
       9.58388672e+01, 9.54560547e+01, 1.12093262e+02, 9.37617188e+01,
       1.11026855e+02, 1.12270996e+02, 1.16542480e+02, 7.96352539e+01,
       9.32016602e+01, 9.46430664e+01, 1.03726074e+02, 9.35410156e+01,
       8.83334961e+01, 1.04615723e+02, 1.00083008e+02, 9.31191406e+01,
       9.39648438e+01, 9.62622070e+01, 9.08247070e+01, 9.28339844e+01,
       9.21923828e+01, 1.14282715e+02, 1.10676270e+02, 9.17153320e+01,
       1.12709473e+02, 1.14214844e+02, 1.05361328e+02, 1.05449707e+02,
       9.32280273e+01, 1.11850098e+02, 9.09575195e+01, 1.11875977e+02,
       9.46821289e+01, 9.56274414e+01, 9.29321289e+01, 1.11284668e+02,
       9.06494141e+01, 1.03776367e+02, 1.11851074e+02, 1.11927734e+02,
       8.28295898e+01, 1.02212402e+02, 1.03971191e+02, 9.10703125e+01,
       1.06122070e+02, 9.37744141e+01, 9.75126953e+01, 1.10212891e+02,
       1.04788574e+02, 9.38554688e+01, 9.05283203e+01, 1.06781250e+02,
       8.51502279e+11, 9.66259766e+01, 1.17541016e+02, 1.11875488e+02,
       9.58325195e+01, 1.15616699e+02, 7.82055664e+01, 9.33520508e+01,
       1.16707520e+02, 1.11506836e+02, 9.01059570e+01, 1.15157715e+02,
       9.55258789e+01, 9.77749023e+01, 1.10305176e+02, 9.39028320e+01,
       1.05623535e+02, 9.08911133e+01, 9.63637695e+01, 1.01278320e+02,
       9.41801758e+01, 1.09769043e+02, 1.07292969e+02, 1.05937500e+02,
       9.03881836e+01, 9.53862305e+01, 9.41289062e+01, 1.09596680e+02,
       1.09662598e+02, 9.92182617e+01, 9.53735352e+01, 1.03878418e+02,
       9.53666992e+01, 9.55083008e+01, 1.07219238e+02, 9.38911133e+01,
       9.47553711e+01, 1.00074219e+02, 1.04940918e+02, 1.11108887e+02,
       9.31972656e+01, 1.06368164e+02, 9.49819336e+01, 1.07977539e+02,
       7.87377930e+01, 1.11688965e+02, 9.11713867e+01, 1.10217285e+02,
       8.98818359e+01, 1.11662598e+02, 9.62646484e+01, 1.03879395e+02,
       1.18637695e+02, 9.52114258e+01, 9.40317383e+01, 1.07906738e+02,
       1.03119629e+02, 9.96694336e+01, 1.00975098e+02, 1.11959473e+02,
       1.05687988e+02, 1.08153320e+02, 9.31215820e+01, 1.13062988e+02,
       9.61811523e+01, 9.39916992e+01, 1.04093262e+02, 9.28413086e+01,
       9.66586914e+01, 9.53442383e+01, 9.38515625e+01, 9.37792969e+01,
       7.50712891e+01, 9.16679688e+01, 1.19490723e+02, 9.20268555e+01,
       1.03151855e+02, 9.42924805e+01, 1.01125488e+02, 9.59135742e+01,
       9.63784180e+01, 1.09162598e+02, 1.07221191e+02, 1.00552246e+02,
       1.05128906e+02, 9.73227539e+01, 9.28784180e+01, 1.11251953e+02,
       1.22731445e+02, 1.17491699e+02, 9.54199219e+01, 1.10477051e+02,
       1.03817871e+02, 1.03387207e+02, 1.06472168e+02, 9.13867188e+01,
       9.10024414e+01, 9.40654297e+01, 1.19024414e+02, 9.23945312e+01,
       9.45239258e+01, 9.08442383e+01, 9.51499023e+01, 1.03057617e+02,
       9.28217773e+01, 9.72016602e+01, 9.25336914e+01, 1.09495605e+02,
       1.17306152e+02, 9.54165039e+01, 1.10243652e+02, 9.49790039e+01,
       9.68950195e+01, 9.02724609e+01, 9.48427734e+01, 9.44716797e+01,
       9.02465820e+01, 9.30566406e+01, 9.08784180e+01, 9.22778320e+01,
       9.10297852e+01, 9.65673828e+01, 1.12564941e+02, 9.08574219e+01,
       1.11615723e+02, 9.53769531e+01, 9.03344727e+01, 1.08583008e+02,
       1.13483398e+02, 9.36655273e+01, 1.22036621e+02, 9.20913086e+01,
       1.05726074e+02, 9.51669922e+01, 1.12558105e+02, 9.47431641e+01,
       1.06933594e+02, 9.26518555e+01, 1.12009277e+02, 9.63486328e+01,
       9.48281250e+01, 1.04803223e+02, 9.38051758e+01, 1.02249023e+02,
       1.10692383e+02, 9.57817383e+01, 9.46245117e+01, 1.08645508e+02,
       8.84033203e+01, 1.13175293e+02, 9.22456055e+01, 1.16704590e+02,
       1.10666016e+02, 8.95786133e+01, 1.01549316e+02, 8.74575195e+01,
       9.13994141e+01, 9.54633789e+01, 9.27602539e+01, 9.60444336e+01,
       1.00350098e+02, 9.18457031e+01, 9.48647461e+01, 9.32778320e+01,
       9.67509766e+01, 1.04536621e+02, 7.68193359e+01, 9.49790039e+01,
       1.01734863e+02, 1.04006348e+02, 8.91635742e+01, 9.11088867e+01,
       9.30527344e+01, 1.06855469e+02, 8.05483398e+01, 1.12020020e+02,
       1.12638184e+02, 1.10802734e+02, 9.57983398e+01, 1.10608887e+02,
       1.10259766e+02, 9.61176758e+01, 1.08099609e+02, 7.65996094e+01,
       9.12612305e+01, 1.05369141e+02, 9.28144531e+01, 9.29106445e+01,
       9.47299805e+01, 1.17798340e+02, 1.07950684e+02, 9.52763672e+01,
       9.17153320e+01, 9.40805664e+01, 1.08094238e+02, 1.07645996e+02,
       9.97812500e+01, 1.13630371e+02, 9.32949219e+01, 9.36528320e+01,
       8.99838867e+01, 9.48208008e+01, 9.78833008e+01, 1.10940918e+02,
       9.34726562e+01, 1.10663086e+02])

In [32]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred, y_test)

1.6910044773544357e+21

Above high value of MSE (1.69) suggests the biasedness or high variance or both in the given dataset.
Therefore, the model is not best fit for the given dataset.

To remove the biasedness in the dataset performing the Principal Component analysis. PCA will help to reduce the dimensionality of the given dataset

### Performing PCA

In [33]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 'mle')
pca.fit(X_train)

PCA(n_components='mle')

In [34]:
pca.explained_variance_ratio_

array([3.81270883e-01, 2.14797517e-01, 1.32790472e-01, 1.18981873e-01,
       9.21027087e-02, 1.59702484e-02, 7.51224810e-03, 4.32566641e-03,
       2.94233662e-03, 2.41569033e-03, 2.36225481e-03, 2.07776071e-03,
       1.67484430e-03, 1.49616806e-03, 1.29875525e-03, 1.02977728e-03,
       9.52285227e-04, 8.90574218e-04, 7.99046329e-04, 7.27765175e-04,
       6.46244986e-04, 6.19201915e-04, 5.81315875e-04, 5.13638978e-04,
       4.96940089e-04, 4.34152731e-04, 4.05301443e-04, 3.80823107e-04,
       3.78072989e-04, 3.51024532e-04, 3.27872632e-04, 3.19533644e-04,
       2.99674893e-04, 2.83288386e-04, 2.69766191e-04, 2.44592498e-04,
       2.23415036e-04, 2.18367572e-04, 2.09092249e-04, 1.94361862e-04,
       1.88187849e-04, 1.80322404e-04, 1.76332015e-04, 1.73014496e-04,
       1.70087396e-04, 1.52415111e-04, 1.47780523e-04, 1.44702137e-04,
       1.42088498e-04, 1.39884285e-04, 1.34418476e-04, 1.28411949e-04,
       1.26629027e-04, 1.21300894e-04, 1.15979506e-04, 1.10000630e-04,
       1.08261693e-04, 1.02836467e-04, 1.01193004e-04, 9.86871934e-05,
       9.24408813e-05, 9.00827688e-05, 8.55407819e-05, 8.55159282e-05,
       8.06033955e-05, 7.73145463e-05, 7.65812365e-05, 7.60404325e-05,
       7.07956599e-05, 7.05623038e-05, 6.88262221e-05, 6.60974588e-05,
       6.38742851e-05, 6.15396989e-05, 6.08003084e-05, 6.04709859e-05,
       5.85022346e-05, 5.76086448e-05, 5.52991625e-05, 5.48527034e-05,
       5.36361615e-05, 5.17018780e-05, 4.99630709e-05, 4.86918124e-05,
       4.76789993e-05, 4.66417551e-05, 4.45483834e-05, 4.44475639e-05,
       4.35091982e-05, 4.29206206e-05, 4.17450186e-05, 4.00928146e-05,
       3.91669383e-05, 3.77418690e-05, 3.74035667e-05, 3.65830076e-05,
       3.51100399e-05, 3.45863879e-05, 3.38946182e-05, 3.30384666e-05,
       3.21688051e-05, 3.17873839e-05, 3.06757133e-05, 2.88111744e-05,
       2.84513856e-05, 2.79489179e-05, 2.69391563e-05, 2.64477622e-05,
       2.62521835e-05, 2.58147277e-05, 2.42679123e-05, 2.40050017e-05,
       2.32867140e-05, 2.27959673e-05, 2.21135020e-05, 2.17279801e-05,
       2.13336751e-05, 2.07291450e-05, 2.01577625e-05, 1.92588383e-05,
       1.87777939e-05, 1.84635248e-05, 1.79351131e-05, 1.71951339e-05,
       1.66279065e-05, 1.60298960e-05, 1.56458464e-05, 1.54906928e-05,
       1.53935415e-05, 1.52008886e-05, 1.50368193e-05, 1.44387301e-05,
       1.41779243e-05, 1.36362264e-05, 1.30681034e-05, 1.28834715e-05,
       1.25907293e-05, 1.20997578e-05, 1.18249051e-05, 1.16996440e-05,
       1.08071059e-05, 1.06466908e-05, 1.03257022e-05, 9.85024789e-06,
       9.64088491e-06, 9.45951765e-06, 9.38045651e-06, 8.86665869e-06,
       8.68143983e-06, 8.49545273e-06, 8.23554748e-06, 8.16523380e-06,
       7.87529537e-06, 7.78743865e-06, 7.43883543e-06, 7.18484250e-06,
       7.03742380e-06, 6.77819122e-06, 6.52296464e-06, 6.44509383e-06,
       6.33925809e-06, 6.11874947e-06, 6.07172750e-06, 5.83999830e-06,
       5.69800163e-06, 5.53130701e-06, 5.40316641e-06, 5.33875122e-06,
       5.23255951e-06, 5.06732718e-06, 4.90396729e-06, 4.76445888e-06,
       4.60069011e-06, 4.34868439e-06, 4.25165236e-06, 4.09406688e-06,
       3.83110279e-06, 3.55232499e-06, 3.45684733e-06, 3.40552569e-06,
       3.36349720e-06, 3.21140113e-06, 3.18420715e-06, 3.10058710e-06,
       2.98572097e-06, 2.88701925e-06, 2.80058320e-06, 2.75371877e-06,
       2.62867847e-06, 2.50075129e-06, 2.40266846e-06, 2.34505650e-06,
       2.30327681e-06, 2.27353755e-06, 2.18009155e-06, 2.15683556e-06,
       2.03725889e-06, 2.00937041e-06, 1.99226263e-06, 1.92299174e-06,
       1.87724405e-06, 1.85412971e-06, 1.78760097e-06, 1.74147685e-06,
       1.62105340e-06, 1.59166328e-06, 1.51610181e-06, 1.42105493e-06,
       1.34288532e-06, 1.29739798e-06, 1.20771404e-06, 1.15156303e-06,
       1.11954928e-06, 1.08314718e-06, 1.05953674e-06, 1.05018309e-06,
       1.02465135e-06, 1.00711004e-06, 9.50501378e-07, 9.37634175e-07,
       9.21385427e-07, 8.79875851e-07, 8.48887606e-07, 8.38292238e-07,
       8.03201506e-07, 7.96714574e-07, 7.63997915e-07, 7.44763762e-07,
       7.24043685e-07, 7.07481520e-07, 6.79167226e-07, 6.61210274e-07,
       6.36335534e-07, 5.85514410e-07, 5.21842666e-07, 5.01266561e-07,
       4.92585471e-07, 4.90382909e-07, 4.52883024e-07, 4.35475661e-07,
       4.22602800e-07, 3.95388571e-07, 3.91837219e-07, 3.85045959e-07,
       3.54964984e-07, 3.27350093e-07, 2.46671792e-07, 2.06026581e-07,
       1.97702073e-07, 1.85173311e-07, 1.43943543e-07, 1.22978483e-07,
       1.10620958e-07, 7.74091018e-08, 5.70629709e-08])

In [35]:
X_train_transformed = pca.transform(X_train)
X_test_transformed = pca.transform(X_test)

In [36]:
X_train_transformed.shape

(3367, 255)

As shown above the PCA has reduced the features from 376 to 255.

### Performing the linear regression on the data derived from the PCA

In [37]:
Lireg2 = LinearRegression()
Lireg2.fit(X_train_transformed, y_train)

LinearRegression()

In [38]:
y_pred2 = Lireg2.predict(X_test_transformed)
y_pred2

array([ 91.9880601 ,  93.45095176, 110.7172765 ,  95.60065046,
       106.71284444, 111.54849459, 111.71033837,  92.10591035,
        94.94336768,  96.27840657,  95.70616151, 117.88870969,
        95.59558187,  96.69363425, 106.46079618, 105.77608512,
        97.58282712,  92.8025246 , 104.3631028 , 105.13569259,
       111.46906824, 109.89078912,  93.19081601,  95.20339755,
        91.61335561,  94.61302909,  93.0777551 ,  93.87721749,
        93.5447986 , 108.58915336, 111.84816398, 109.40953005,
        87.10368098,  95.0966806 ,  77.46308038, 111.96702989,
       107.78450425,  94.63067239, 110.86608185,  93.98258733,
       111.73978511, 104.82137409,  93.37121361,  95.37225503,
        98.82221751, 110.4110682 , 112.9927015 , 104.77549491,
        93.00670246,  94.200985  ,  89.42066662,  96.27335936,
       108.25310625, 109.16553192, 112.321073  , 102.76123575,
        95.21076694,  93.84327552,  91.26447018,  92.73227928,
        94.24528119,  94.28757139, 111.24220353, 111.5650691 ,
       106.5814746 ,  93.9015013 ,  96.70202547,  94.59684603,
        88.09755909, 112.30412529,  93.69984844,  78.24412516,
       111.72831137, 110.42655218,  92.48625056,  96.54377905,
       112.87434174,  93.71307279,  74.27831856, 115.23851772,
        77.47772896, 112.08446361, 112.21705848, 114.35609734,
       116.58021568,  91.27190007, 111.07045851,  72.44537598,
        97.59780915,  96.55218677,  93.64761126,  90.46893283,
        92.7828691 ,  93.61513614, 103.53979659,  93.51058223,
       116.09913425,  93.45001335,  95.94178997,  96.3341665 ,
       120.06734945, 111.84879479, 108.24241834,  95.56328439,
        99.81175741, 112.15235685, 115.91314375,  95.37676146,
        95.42629525, 113.39916783, 108.61483127,  79.07199004,
        96.83144746, 111.68023449, 101.85033497,  95.6584472 ,
       105.95889857,  92.82255406, 110.6628422 ,  91.91619282,
        92.66445251, 109.92348528, 109.48277297, 100.36399628,
       103.22816874, 113.11385621,  92.40693944,  93.86752477,
       110.76939236, 113.57584898,  93.96701656, 109.72049875,
       108.40459065, 111.59790262,  95.6998114 ,  95.92225312,
       111.0129629 ,  90.81837431,  95.69776276, 100.36399628,
        92.94249795, 113.29895641, 111.60514138, 113.32335507,
       112.71439389, 110.0373248 ,  89.98901145, 112.45591892,
        77.88268016, 108.15727557,  95.20339755, 113.06304305,
        92.84518464,  90.585497  ,  95.50849795,  94.16947493,
       104.08655716,  94.02521222, 113.79790229, 102.61743216,
        94.43310842, 111.29206545,  88.93002785,  96.56561093,
       111.3422116 , 111.75351927, 116.63515464, 103.06279816,
       108.61388231,  93.67584856, 109.43669471,  91.10884296,
       115.84056755, 112.0519463 ,  84.03501466, 104.69368129,
       100.50218777,  95.87284715,  90.61750751,  97.44172667,
        91.44818491,  97.22116918,  91.24829661, 109.65237971,
       112.9499259 , 111.07106243,  93.92853657, 104.11969469,
       111.28849909, 113.41448185,  95.9049601 ,  95.20530352,
        87.99319924, 108.95859293,  95.53244985,  97.44828274,
       111.34234858, 111.99811005, 111.67137566, 100.20883831,
       108.93601067,  86.70069278, 105.93428329, 106.66527984,
       112.15851436,  94.80290626,  95.53993804,  95.92792871,
        97.37110781,  95.04576548, 105.02620831, 112.74776038,
       110.56601534, 113.07416421, 113.24833436, 110.58643624,
       113.22539479,  98.44985783, 107.29377022,  91.51157923,
       103.03560391,  89.40943125,  79.03866738,  93.33312384,
       113.7533866 , 101.83166352, 101.47000429, 103.14998069,
       111.71033837, 120.07145285,  93.59758433, 121.26993417,
        94.10496744,  90.09049721,  92.90429393,  92.49380715,
       112.36321615,  91.26494744, 106.19011738, 109.00204704,
        94.60944598,  77.62658698, 111.48036676, 117.56093535,
       113.74424909,  89.7024779 ,  97.14771551,  93.60430625,
       105.98566638,  95.65258844, 111.80594621,  93.93576768,
       112.37157489,  93.22584997, 160.23809003,  87.75823957,
       108.10837826,  97.83858826,  94.91412575,  91.71833552,
        95.95595264,  93.28416894, 113.07865013, 112.23123351,
        88.09655682, 117.30331162,  92.90429393, 109.9487876 ,
        93.78716711,  98.89872704,  89.68935918, 102.53801256,
        94.85946827,  95.90943546,  78.34372999,  77.7368069 ,
        94.97194851,  88.41441896,  87.39396509, 102.97296382,
        94.22935407, 103.09459753,  93.23150338, 111.01922211,
       103.58427143, 107.72653223, 114.06079831, 104.78562502,
        94.86030106,  81.74544619,  92.22809487, 118.7797255 ,
       116.61374901,  92.3568983 ,  91.23255519, 110.82235406,
       102.8479019 ,  93.89676788, 105.43814363, 110.0170159 ,
       104.34910755,  95.16406698,  96.80345744,  95.2972351 ,
        95.1726781 , 111.60883845,  94.34574149, 112.78945119,
        95.28022078, 105.91674611, 111.02802707,  95.01435023,
       103.70078643,  89.73994016, 100.40721287,  94.65063437,
        92.36069126,  89.8753507 , 111.38492554,  93.18882286,
        89.86126564,  96.24242538,  92.59280071,  94.41450866,
       112.43090534,  91.10738844, 112.58040025, 110.16417799,
        81.65445088, 111.19998439, 104.98070278, 115.28537591,
        93.32490696, 110.18859686,  96.03533082, 103.41247227,
       113.6802737 , 110.79439153,  95.6690581 ,  95.65897937,
       115.0035663 ,  93.18323594, 106.19515516,  91.92557211,
        90.96229745,  94.36282974,  94.71472033, 106.58948618,
        94.23028217,  90.12983982,  93.87572223, 110.90569186,
        95.72263018, 114.55021083, 107.35066299,  96.92297247,
       111.02659787, 110.10346558, 112.22760779,  97.89817733,
       110.7711482 , 103.84162952,  97.44234474, 112.03093203,
        93.57801081,  92.78886057, 110.49979004, 115.97055047,
       122.94208416,  79.5541326 , 113.16113714,  94.51254995,
        90.83832777, 120.01074043,  93.67216397,  83.50457576,
       113.0416043 ,  92.81877733, 109.43165352,  87.66190296,
        97.2402694 ,  95.69738315, 109.46050316,  89.513368  ,
        95.87062866, 101.63167039, 110.52447155,  96.34148628,
        95.8146219 ,  99.5140225 ,  91.6177943 ,  90.26586487,
        93.0740735 ,  94.18743973, 112.623458  ,  97.66053255,
       113.7748421 ,  94.17071045,  94.29397915, 101.19179284,
        95.04995204, 104.46536818,  96.71242114, 100.61491058,
       105.0297578 , 101.64667422,  92.83940026, 106.1044074 ,
       111.01082885,  93.25311838,  99.64729619,  94.31765233,
        95.01256685,  93.9269987 , 105.36385386,  95.01589426,
       103.06102522,  95.18364704,  92.7586578 , 105.96889971,
        93.59758433,  76.86238972, 112.59542588, 109.42418966,
        93.80164599,  78.13859869, 102.19075881, 104.33105927,
        91.88349517,  93.82386271, 102.65704459,  87.52654232,
       103.78585362, 106.74153349,  97.66776395,  94.76874426,
        92.38911793,  92.77327205,  94.77166273, 110.57030929,
       114.93433905, 109.88651288,  93.55294232, 111.88523484,
        96.10069561, 110.05641214, 104.24595581, 105.90153311,
       111.59687231,  97.35233516,  92.37625238, 108.17314475,
        95.53762561,  98.65385974,  92.49807397, 103.82276237,
        94.80056198, 109.36480958,  92.73062328, 110.61878031,
       104.15683953,  91.39027552,  93.11082412, 114.51370822,
       106.65184459,  94.56154333, 106.82593688, 112.687137  ,
       108.21017679, 111.10436967,  91.05836751,  99.05410589,
       107.97107822, 108.96286293, 104.49368968, 112.89088231,
       107.81606949, 111.75668629,  95.06233149,  92.0209439 ,
       113.10231672,  92.20110522, 104.05692186,  77.29559172,
        94.14880546, 104.54088132,  93.83219243,  94.12197472,
       112.50899483,  91.32825475, 110.21894229, 109.95651321,
       107.16344556,  94.20322125,  95.92904114,  92.89874824,
        96.16344835,  96.65452159, 104.83624876,  87.15055842,
       110.98366573,  95.96092661, 101.39981501,  95.4769132 ,
       112.33449409, 113.61595862, 119.26542481, 110.64607554,
        93.65335618, 112.14216482, 104.05389203,  76.25986233,
        92.79499592, 115.35726577, 110.89742385,  92.39841218,
       112.37716538,  75.52529401, 105.44121003, 103.63817535,
        93.89414139, 113.31366343,  95.35548837,  91.92748304,
        94.54912427, 102.02736012,  93.1948602 , 115.05434254,
       113.42017313,  93.96542756, 113.07865013,  95.84986882,
        77.38373733, 108.78459872,  93.63804737,  93.9267201 ,
       104.75721423, 111.60900958,  73.96365637, 116.91731108,
       113.4408814 ,  95.66790997,  95.25786558, 109.71911706,
        77.25137637, 103.32000262, 111.0811279 , 100.9457535 ,
       101.87414459, 106.7565327 ,  95.70723235,  92.15773949,
        97.15055146, 102.89812237, 115.36285499, 109.47944441,
        92.54915018, 102.62711076, 113.04723489, 119.16234675,
        95.77101448, 108.55411885,  92.46618908, 118.3713057 ,
        96.02619225, 110.0403402 , 104.24500864,  92.09986306,
       112.46658727,  94.86855339, 103.60920988,  91.71382497,
       112.63031   , 102.94137333, 120.44672874,  91.85083495,
        97.51129034, 111.44293018,  95.63169302,  96.11316834,
       119.65746736,  94.3575384 ,  95.77302235,  91.40755959,
        95.84681005,  95.46195292, 112.09164444,  93.76510177,
       111.02618512, 112.2802922 , 116.53451052,  79.62711186,
        93.21061652,  94.64652248, 103.7261419 ,  93.54531808,
        88.34170218, 104.61659377, 100.09493115,  93.11856195,
        93.96353031,  96.25951172,  90.81905242,  92.83179936,
        92.1868256 , 114.29246159, 110.67501718,  91.71833552,
       112.70868326, 114.21800442, 105.35510964, 105.44511629,
        93.22836929, 111.84560506,  90.95731599, 111.88466528,
        94.68615626,  95.6349719 ,  92.92424754, 111.28849909,
        90.64940301, 103.76999776, 111.84879479, 111.92308414,
        82.83540466, 102.19654714, 103.96513233,  91.06849713,
       106.13040912,  93.77271656,  97.5054554 , 110.2127484 ,
       104.78369087,  93.86022579,  90.52569448, 106.78894292,
       117.00406374,  96.6237862 , 117.54534909, 111.87678475,
        95.83498   , 115.62057931,  78.19803331,  93.36478901,
       116.71340276, 111.50364259,  90.1055164 , 115.1603883 ,
        95.52509511,  97.78201982, 110.30047749,  93.91130847,
       105.63027217,  90.88529676,  96.35565955, 101.26594714,
        94.17408615, 109.76201585, 107.28747885, 105.93285168,
        90.39147645,  95.38478616,  94.13676006, 109.59658061,
       109.66001322,  99.2134626 ,  95.37225503, 103.8693135 ,
        95.36765861,  95.51891581, 107.22545326,  93.89441457,
        94.74947376, 100.09299845, 104.93653095, 111.11719749,
        93.20181793, 106.36846562,  94.98481092, 107.9880402 ,
        78.73265395, 111.69531746,  91.16885934, 110.22375352,
        89.88318222, 111.66331189,  96.25700481, 103.87300467,
       118.63630107,  95.21988407,  94.03764129, 107.9182452 ,
       103.12104286,  99.6649056 , 100.98158998, 111.9684055 ,
       105.68601284, 108.15342059,  93.13307533, 113.06304305,
        96.19046419,  93.9903263 , 104.08655716,  92.84533428,
        96.65437992,  95.34295787,  93.84559174,  93.77325687,
        75.07541906,  91.67268546, 119.48997871,  92.03179239,
       103.14668609,  94.2924717 , 101.13358101,  95.90575889,
        96.37030814, 109.17516871, 107.2323521 , 100.55420111,
       105.12272116,  97.32644733,  92.88044467, 111.24490224,
       122.73590318, 117.49090188,  95.42097409, 110.49254193,
       103.81905196, 103.38836457, 106.46601504,  91.38273721,
        91.00966214,  94.06417951, 119.02257515,  92.40371627,
        94.52062255,  90.84592783,  95.15180217, 103.05789827,
        92.82088816,  97.2050225 ,  92.54325527, 109.4919896 ,
       117.3043526 ,  95.41620078, 110.24473085,  94.97226359,
        96.90010504,  90.27047853,  94.84542639,  94.47313182,
        90.251962  ,  93.06577898,  90.88755474,  92.27485744,
        91.02700086,  96.5783652 , 112.55989738,  90.86577431,
       111.61085487,  95.38072233,  90.33228368, 108.58371377,
       113.48654286,  93.66313777, 122.04288245,  92.08945274,
       105.71861272,  95.1594518 , 112.555905  ,  94.74358194,
       106.92814849,  92.65179297, 112.01939981,  96.35297844,
        94.8265817 , 104.79851452,  93.7962005 , 102.23305555,
       110.69016789,  95.78510945,  94.6259719 , 108.64059704,
        88.40782011, 113.18643571,  92.25009324, 116.70164051,
       110.66702929,  89.58399341, 101.54166082,  87.46046412,
        91.39561286,  95.46558602,  92.76245452,  96.0448272 ,
       100.36399628,  91.85846316,  94.86656686,  93.28499124,
        96.75017003, 104.53125894,  76.80989241,  94.98138516,
       101.74809998, 104.00069747,  89.1576298 ,  91.10895604,
        93.04882621, 106.85453162,  80.54897957, 112.01728692,
       112.65040551, 110.80080761,  95.80052916, 110.61138082,
       110.25565945,  96.1247355 , 108.09159432,  76.59124724,
        91.25742137, 105.36032109,  92.81036591,  92.91106668,
        94.72387946, 117.79658203, 107.95429044,  95.28544224,
        91.71833552,  94.08756306, 108.1022565 , 107.63440457,
        99.79292943, 113.62937812,  93.29915814,  93.64701193,
        89.98549606,  94.82989412,  97.89055111, 110.94181727,
        93.4761595 , 110.6628422 ])

In [39]:
mean_squared_error(y_pred2, y_test)

74.0415830671749

Even after performing the PCA, the MSE value of the regression is still high 74.04 which makes the model less reliable.

To avoid the problem of biasedness and overfitting using the XGBoost algorithm

### Performing XGBoost algorithm

In [40]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

In [41]:
grid_values = {'n_estimators': [74,75,76], 'learning_rate': [0.13,0.135,0.14], 'max_depth': [1,2,3]}
grid_xgb = GridSearchCV(xgb.XGBRegressor(), param_grid = grid_values, cv=10, scoring = 'r2')
grid_xgb.fit(X_train_transformed, y_train)

GridSearchCV(cv=10,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, gamma=None,
                                    gpu_id=None, importance_type='gain',
                                    interaction_constraints=None,
                                    learning_rate=None, max_delta_step=None,
                                    max_depth=None, min_child_weight=None,
                                    missing=nan, monotone_constraints=None,
                                    n_estimators=100, n_jobs=None,
                                    num_parallel_tree=None, random_state=None,
                                    reg_alpha=None, reg_lambda=None,
                                    scale_pos_weight=None, subsample=None,
                                    tree_method=None, validate_parameters=None,
                                    verbosity=None),
             param_grid={'learning_rate': [0.13, 0.135, 0.14],
                         'max_depth': [1, 2, 3], 'n_estimators': [74, 75, 76]},
             scoring='r2')

In [42]:
print('Mean score matrix: ', grid_xgb.cv_results_['mean_test_score'])
print('Grid best parameter (max. accuracy): ', grid_xgb.best_params_)
print('Grid best score (accuracy): ', grid_xgb.best_score_)

Mean score matrix:  [0.45764729 0.45814176 0.45913101 0.50777599 0.50801977 0.50839302
 0.51774343 0.51813768 0.51839086 0.46144273 0.46224533 0.46344747
 0.50973091 0.50963463 0.50961485 0.52625844 0.52614744 0.52578019
 0.46411203 0.46503366 0.46574995 0.50883041 0.50891536 0.50932526
 0.52558922 0.52552283 0.52541194]
Grid best parameter (max. accuracy):  {'learning_rate': 0.135, 'max_depth': 3, 'n_estimators': 74}
Grid best score (accuracy):  0.5262584397969535

The given R2 value suggests the variance of the dependent variable explained by the independent variable. A relatively high R2 value here, makes the model best fit.

In [43]:
predict_xgb = grid_xgb.predict(X_test_transformed)

**Saving the final prediction in a CSV file**

In [44]:
Predictions = pd.DataFrame()
Predictions['y'] = pd.Series(predict_xgb)
Predictions.to_csv('Predictions.csv')
Predictions

              y
0     92.495544
1     97.489349
2    115.287903
3     97.873123
4    102.426994
..          ...
837   95.435631
838   97.034935
839  112.611992
840   94.571243
841  108.469093

[842 rows x 1 columns]